### PR TITLE
Developer

### PR DESCRIPTION
**Pull request by Patriboom**
Here are some changes on

- Comment: now you can add percent of work done, when you reach some point, the according tag is attached to the issue ( 10%: on progress; 80%: testing, 100%: closed )
Those percentages are customable.

- The todo page now works properly, showing issues to do, in progress, under testing, and closed

- The sidebar works with tags numbers instead of hard-text programming.  That means, you can now customize the status tags and keep following the issues open or closed.

### CODE REVIEW

**Comment by julianatienza** [comment]
Hello Patriboom. I'd like so much to see this project alive (but pixeline said it's discontinued for free-time lack)... how can i help with this? 

I've installed it today and i think it's very useful and easy to use in comparation with mantis, redmine or other commercial products. 

There is also some bugs pending to fix (f.e. the mail issue that i think could be easy to find and fix with some knowledge of php that i still haven't)...

**Comment by Patriboom** [comment]
Hello Juliana, 

	I wonder how you found my email address.  Great job!

	I did some patches on the bugs project, but I don't expect to
work a lot on it. It works well, well enough for me. 

	I did plan some update:
		- email system on track
		- ability to change the labels on the fly

	Otherwise, nothing.
	If you have ideas, you can submit them, but I can not promise
to work on that.

	You ask about how you can help on the project. Three things can I suggest you:
	1) to produce the translation for your native language
	2) try and comment the modifications (beta tester)
	3) submit ideas for new functions


	Did you download the branch I posted on github ? 
	What do you think about the percentage of work done?
	What do you think about the new « Todo List »  ?

**Comment by julianatienza** [comment]
Thanks for your reply, Patrock. 

I'm setting up a new platform and i will try the code with your changes (i'm still near to newbie with github, i'm working still with subversion and cvs ... i know. It'st time to upgrade my old skills). 

Thanks so much for your efforts.

- Translations: Tell me the way it's supported here. Is there any kind of file with locals terms? I will be pleased to translate from english to spanish. 
- WishList:
   - One issue is only assigned to one person. I missed the possibility of assign issues to more than one person (perhaps some kind of watchers of the issue that wanted to be emailed if something has changed). 
- Reports? or any way to see at least one realtionship between issues and solving time individually (not like one general average of the issues in the project like nowaday does)
- TimeZone... or at least GMT references. The best would be a new config setting for administrators.
- I've seen that when you create one user always appears with the default language "de". i think it's a bug. 

Pleased to meet you, 

Best Regards

**Comment by Patriboom** [comment]
Juliana, 

to work on translation:
 - open those files:    app/application/language/ES/  (all of them)
                                 app/application/language/EN/  (all of them)

update the      app/application/language/ES/  (all of them)   files only
use the english ones (EN) as references.
The system is done on such way if it does find the ES information, it will use the EN
So, to make a complete translation, you must be sure that every single variable in EN also appears in ES

For exemple.

EN file has
   'welcome' => 'Welcome',
	'users' => 'Users',
	'administration' => 'Administration',
	'logout' => 'Logout',
	'dashboard' => 'Dashboard',
       [...]

but ES file has
   'welcome' => 'Welcome',
	'users' => 'Users',
	'administration' => 'Administration',
	'logout' => 'Logout',
       [...]

The spanish user will read "Dashboad" in english every single time the word is supposed to appear in spanish becuse the ES file doesn't define the value for 'dashboard' variable.

This said, you undestoot that evey line as two main parts:   variable => value
You must keep INTACT the variable name
You translate ONLY the value.

Example, the spanish content should be
   'welcome' => 'Bienvenido',
	'users' => 'Usarios',
	'administration' => 'Administración',
	'logout' => 'Salir',
	'dashboard' => 'Vista global',
      [...]

In my brach, their is not a single file in ES, not even a directory.  
So fist copy EN directory (with all files) into ES directory and work on the new ES files.

**Comment by julianatienza** [comment]
Perfect. Don't worry, i'm programmer and i've used properties files in Java. It's used in the same way (key, value). 

I will keep you in touch!

**Comment by Patriboom** [comment]
About default language for new user.  
I invite to the set it throu you phpmyadmin in the table « users », line language.  Use the international 2 letters code.

**Comment by Patriboom** [comment]
eMail me your files to patrick at cartefoi dot net
I'will integrate them into the project while my pull request are waiting.

**Comment by Patriboom** [comment]
Language's wish, from Juliana is fullfilled. Administrator who create new user may now create this user with a particular language.

**Comment by Patriboom** [comment]
I'll start working on email issue.
Please set me as user in your system and change status of some ticket, assign me some ticket.
I want to see if any email will be sent to me.
Use this email:  patrick at cartefoi dot net

**Comment by Patriboom** [comment]
Please si « Project » section and comment to make sure we will all work to the same destination.

**Comment by pixeline** [comment]
Hello all, I'm happy to pass over the project onto people who feel they have both the time, the interest and the competences required. @Patriboom I've set you as project collaborator, but you can also just fork it and create your own "product" out of it. Bugs was intended to be simple enough for non-web people (my customers) to be able to fill in an issue, without having to think about project management. And it achieved that goal. I don't really see the points in the features you ask (progress report, etc). It makes me think of JIRA, which is a PITA to work with: I feel i spend more time describing my work than actually getting things done. Of course I may be wrong, but i just wanted to warn you of the dangers of "featuritis". Anyways, as I said repeatedly, I don't want to maintain this project anymore, because it is based on Laravel which has become bloated. I'm working on a new bug system based on the awesome fatfree framework. 

So anyway, I guess I'm just trying to say "bye, have fun with it" :) @Patriboom you're in charge now!

**Comment by Patriboom** [comment]
Thanks for all your workk @pixeline 
I'm surprised t be in charge, I'll try to do as you: my best not much.
Project I listed were only the transcription of « wishlist » made by some users.
The goal of « Bugs » is - as you say - fullfiled.  So whatever more is for fun.

**Comment by Patriboom** [comment]
Ouf!  Big deal.  I'm not sure to want to say «Thanks!» for this duty, but I'm sure to want to say thanks for all the work done by you, @pixeline  (Alexandre) and others.  Big job done.

**Comment by Patriboom** [comment]
@julianatienza  you wrote: 

> One issue is only assigned to one person. I missed the possibility of assign issues to more than one person (perhaps some kind of watchers of the issue that wanted to be emailed if something has changed).

But it seams to already exist.
You just add a user to a whole project.
addusertoproject

What more do you want ?

**Pull request closed without merging**
