### PR TITLE
uploading file without flash

### PR DESCRIPTION
**Pull request by Patriboom**
Many changes, 
to make it work, make sure you insert this line into activity table
INSERT IGNORE INTO `activity` (`id`, `description`, `activity`) VALUES  ('7', 'Attached a file to issue', 'attached-file');

### CODE REVIEW

**Comment by marcelloinfoweb** [comment]
Guy, you need to test the application on php5 and php7, because not everyone uses php7 yet, and even running well, on other php versions will break.

So to avoid being opened several issues, make that effort, please.

His work is spectacular and I am willing to help, but I do not have programming skills, my knowledge is limited.

**Thank you for your attention**.

**Comment by marcelloinfoweb** [comment]
I am uploading files by the new update, the files go to the directory, but they are not fixed in the new comment.

**Comment by Patriboom** [comment]
No, the new version doesn't attach to comment, but insert the file in between comments

**Comment by Patriboom** [comment]
I've just put it back: uploaded files attached to the comment; but .... the new way to attach files will attach it to the previous comment.
What's the best ?

**Comment by marcelloinfoweb** [comment]
For the sake of organization, it is better to be together with the comment, because if the Issue has many comments it is difficult to associate from which attachment it is of which comment.

**Pull request merged**
